---
- name: Setup Logstash Forwarder on the instance
  hosts: logstash-forwarder
  user: root
  # remote_user: user
  # sudo: yes

  vars:
    app_name: lumberjack

  roles:
    - { role: logstash-forwarder, tags: [ 'logstash-forwarder' ] }